import prisma from "@/app/lib/prisma";
import { Alert } from "@prisma/client";
import {
  buildManageUrl,
  buildMeetingUrl,
  sendInterestAreaEmail,
  sendMeetingPublishedEmail,
  sendUpcomingMeetingEmail,
} from "@/app/lib/email";
import {
  getAdminRecipients,
  getCityUpdateRecipients,
  getInterestAreaRecipients,
  getPublishMeeting,
} from "@/app/lib/publish";

/**
 * Two-stage alert pipeline shared by every alert type:
 *   1. create*Alert() snapshots the change as a DRAFTED Alert.
 *   2. sendAlertToAdmins() emails the draft to admins for review (SENT_TO_ADMINS).
 *   3. publishAlertToSubscribers() is the admin's manual trigger to notify
 *      end-user subscribers with the reviewed content (PUBLISHED).
 *
 * Supported alert types:
 *   - MEETING_UPDATED — "this meeting happened" post-meeting summary
 *   - MEETING_UPCOMING — "this meeting is coming up" pre-meeting agenda preview
 *   - INTEREST_AREA_UPDATED — a topic of interest was discussed at a meeting
 *
 * @module alerts
 */

// ---------------------------------------------------------------------------
// AlertContent — discriminated by the companion Alert.type column
// ---------------------------------------------------------------------------

/** Content for a MEETING_UPDATED alert ("this meeting happened"). */
export type MeetingUpdatedContent = {
  subject: string;
  tldr: string | null;
  keyDecisions: string[];
};

/**
 * Content for a MEETING_UPCOMING alert ("this meeting is coming up").
 * Structured as three reading-depth tiers:
 *   bite  — one-line teaser (the quickest possible read)
 *   snack — short paragraph for a casual reader
 *   meal  — fuller narrative for someone who wants the full picture
 */
export type MeetingUpcomingContent = {
  subject: string;
  bite: string;
  snack: string;
  meal: string;
};

/** Content for an INTEREST_AREA_UPDATED alert ("topic discussed at a meeting"). */
export type InterestAreaUpdatedContent = {
  subject: string;
  tldr: string | null;
  highlights: string[];
};

/** Union of all alert content shapes, discriminated by Alert.type. */
export type AlertContent =
  | MeetingUpdatedContent
  | MeetingUpcomingContent
  | InterestAreaUpdatedContent;

export type AlertSendResult = { sent: number; failed: string[] };

// ---------------------------------------------------------------------------
// Alert creators
// ---------------------------------------------------------------------------

/** Creates a DRAFTED alert snapshotting a meeting's current post-meeting content. */
export async function createMeetingUpdateAlert(meetingId: number): Promise<Alert> {
  const meeting = await getPublishMeeting(meetingId);
  if (!meeting) throw new Error(`Meeting ${meetingId} not found`);

  const content: MeetingUpdatedContent = {
    subject: meeting.title,
    tldr: meeting.tldr,
    keyDecisions: meeting.keyDecisions,
  };

  return prisma.alert.create({
    data: {
      type: "MEETING_UPDATED",
      meetingId,
      content,
      status: "DRAFTED",
    },
  });
}

/**
 * Creates a DRAFTED alert for an upcoming meeting.
 * The bite/snack/meal tiered summary is generated by the Python scraper and
 * passed in — this function only persists and routes it.
 */
export async function createMeetingUpcomingAlert(
  meetingId: number,
  tiers: Pick<MeetingUpcomingContent, "bite" | "snack" | "meal">,
): Promise<Alert> {
  const meeting = await getPublishMeeting(meetingId);
  if (!meeting) throw new Error(`Meeting ${meetingId} not found`);

  const content: MeetingUpcomingContent = {
    subject: meeting.title,
    ...tiers,
  };

  return prisma.alert.create({
    data: {
      type: "MEETING_UPCOMING",
      meetingId,
      content,
      status: "DRAFTED",
    },
  });
}

/**
 * Creates a DRAFTED alert for an interest area update.
 * The summary content is derived from the InterestArea's current statusSummary.
 */
export async function createInterestAreaAlert(interestAreaId: number): Promise<Alert> {
  const area = await prisma.interestArea.findUnique({
    where: { id: interestAreaId },
    select: { name: true, statusSummary: true },
  });
  if (!area) throw new Error(`InterestArea ${interestAreaId} not found`);

  const content: InterestAreaUpdatedContent = {
    subject: area.name,
    tldr: area.statusSummary ?? null,
    highlights: [],
  };

  return prisma.alert.create({
    data: {
      type: "INTEREST_AREA_UPDATED",
      interestAreaId,
      content,
      status: "DRAFTED",
    },
  });
}

// ---------------------------------------------------------------------------
// Pipeline stages
// ---------------------------------------------------------------------------

/** Emails the draft to admin subscribers for review. */
export async function sendAlertToAdmins(alertId: number): Promise<AlertSendResult> {
  const alert = await prisma.alert.findUnique({ where: { id: alertId } });
  if (!alert) throw new Error(`Alert ${alertId} not found`);

  const result = await sendAlertEmails(alert, await getAdminRecipients(), {
    isAdmin: true,
  });

  await prisma.alert.update({
    where: { id: alertId },
    data: { status: "SENT_TO_ADMINS", sentToAdminsAt: new Date() },
  });

  return result;
}

/** Admin's manual trigger: sends the reviewed content to end-user subscribers. */
export async function publishAlertToSubscribers(
  alertId: number,
  triggeredBy?: string,
): Promise<AlertSendResult> {
  const alert = await prisma.alert.findUnique({ where: { id: alertId } });
  if (!alert) throw new Error(`Alert ${alertId} not found`);

  const recipients = await getSubscriberRecipients(alert);
  const result = await sendAlertEmails(alert, recipients, { isAdmin: false });

  await prisma.alert.update({
    where: { id: alertId },
    data: {
      status: "PUBLISHED",
      publishedAt: new Date(),
      publishedBy: triggeredBy ?? null,
    },
  });

  return result;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

async function getSubscriberRecipients(alert: Alert) {
  switch (alert.type) {
    case "MEETING_UPDATED":
    case "MEETING_UPCOMING": {
      if (!alert.meetingId) throw new Error(`Alert ${alert.id} is missing meetingId`);
      const meeting = await prisma.meeting.findUniqueOrThrow({
        where: { id: alert.meetingId },
        select: { cityId: true },
      });
      return getCityUpdateRecipients(meeting.cityId);
    }
    case "INTEREST_AREA_UPDATED": {
      if (!alert.interestAreaId)
        throw new Error(`Alert ${alert.id} is missing interestAreaId`);
      return getInterestAreaRecipients(alert.interestAreaId);
    }
  }
}

async function sendAlertEmails(
  alert: Alert,
  recipients: { email: string; unsubscribeToken: string | null }[],
  opts: { isAdmin: boolean },
): Promise<AlertSendResult> {
  let sent = 0;
  const failed: string[] = [];

  switch (alert.type) {
    case "MEETING_UPDATED": {
      if (!alert.meetingId) throw new Error(`Alert ${alert.id} is missing meetingId`);
      const meeting = await prisma.meeting.findUniqueOrThrow({
        where: { id: alert.meetingId },
        select: { slug: true, city: { select: { name: true } } },
      });
      const content = alert.content as MeetingUpdatedContent;
      const meetingUrl = buildMeetingUrl(meeting.slug);
      for (const recipient of recipients) {
        try {
          await sendMeetingPublishedEmail({
            to: recipient.email,
            meetingTitle: content.subject,
            cityName: meeting.city.name,
            tldr: content.tldr,
            keyDecisions: content.keyDecisions,
            meetingUrl,
            manageUrl: recipient.unsubscribeToken
              ? buildManageUrl(recipient.unsubscribeToken)
              : undefined,
            isAdmin: opts.isAdmin,
          });
          sent += 1;
        } catch (err) {
          console.error(`Failed to send alert email to ${recipient.email}`, err);
          failed.push(recipient.email);
        }
      }
      break;
    }

    case "MEETING_UPCOMING": {
      if (!alert.meetingId) throw new Error(`Alert ${alert.id} is missing meetingId`);
      const meeting = await prisma.meeting.findUniqueOrThrow({
        where: { id: alert.meetingId },
        select: { slug: true, date: true, city: { select: { name: true } } },
      });
      const content = alert.content as MeetingUpcomingContent;
      const meetingUrl = buildMeetingUrl(meeting.slug);
      for (const recipient of recipients) {
        try {
          await sendUpcomingMeetingEmail({
            to: recipient.email,
            meetingTitle: content.subject,
            cityName: meeting.city.name,
            meetingDate: meeting.date,
            bite: content.bite,
            snack: content.snack,
            meal: content.meal,
            meetingUrl,
            manageUrl: recipient.unsubscribeToken
              ? buildManageUrl(recipient.unsubscribeToken)
              : undefined,
            isAdmin: opts.isAdmin,
          });
          sent += 1;
        } catch (err) {
          console.error(`Failed to send upcoming alert email to ${recipient.email}`, err);
          failed.push(recipient.email);
        }
      }
      break;
    }

    case "INTEREST_AREA_UPDATED": {
      if (!alert.interestAreaId)
        throw new Error(`Alert ${alert.id} is missing interestAreaId`);
      const area = await prisma.interestArea.findUniqueOrThrow({
        where: { id: alert.interestAreaId },
        select: { slug: true, city: { select: { name: true, stateCode: true } } },
      });
      const content = alert.content as InterestAreaUpdatedContent;
      // TODO: build a proper interest-area URL once the Topics page exists
      const areaUrl = `${process.env.NEXT_PUBLIC_SITE_URL ?? ""}`;
      for (const recipient of recipients) {
        try {
          await sendInterestAreaEmail({
            to: recipient.email,
            areaName: content.subject,
            cityName: area.city.name,
            tldr: content.tldr,
            highlights: content.highlights,
            areaUrl,
            manageUrl: recipient.unsubscribeToken
              ? buildManageUrl(recipient.unsubscribeToken)
              : undefined,
            isAdmin: opts.isAdmin,
          });
          sent += 1;
        } catch (err) {
          console.error(
            `Failed to send interest-area alert email to ${recipient.email}`,
            err,
          );
          failed.push(recipient.email);
        }
      }
      break;
    }
  }

  return { sent, failed };
}
